{
    'name': 'Mini Inventory',
    'version': '18.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Mini inventory module for learning Odoo concepts',
    'depends': ['base'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/location_data.xml',
        'views/product_views.xml',
        'views/location_views.xml',
        'views/move_views.xml',
        'views/picking_views.xml',
        'views/quant_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
}